question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
    {"text": "Goldfish have a memory span of only three seconds.", "answer": "False"},
    {"text": "The Eiffel Tower can grow more than six inches during the summer.", "answer": "True"},
    {"text": "Polar bears have black skin under their white fur.", "answer": "True"},
    {"text": "The fastest land animal is the cheetah.", "answer": "True"},
    {"text": "Humans share about 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.", "answer": "True"},
    {"text": "Venus is the hottest planet in the Solar System.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "There are 206 bones in the adult human body.", "answer": "True"},
    {"text": "Penguins can fly in short bursts.", "answer": "False"},
    {"text": "The blue whale is the largest animal to ever exist on Earth.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Humans can survive without water for up to two weeks.", "answer": "False"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"}
]